FROM scimma/base:0.0
RUN yum -y install python3-devel.x86_64 python3-pip.noarch
RUN cd /usr/local/src && \
    git clone https://github.com/confluentinc/confluent-kafka-python.git && \
    cd confluent-kafka-python && \
    git checkout v1.3.0 && \
    python3 setup.py build  && \
    python3 setup.py install  
RUN mkdir -p /root/.config && ln -s /root/shared/kafkacat.conf /root/.config/kafkacat.conf
WORKDIR /usr/bin
CMD ["/bin/bash"]
