FROM scimma/base:0.0
RUN yum -y install python3-devel.x86_64 python3-pip.noarch && pip3 install confluent_kafka
COPY scripts/runClient /root/runClient
RUN chmod ugo+rx /root/runClient
RUN mkdir -p /root/.config && ln -s /root/shared/kafkacat.conf /root/.config/kafkacat.conf
WORKDIR /usr/bin
CMD ["/bin/bash"]
