FROM scimma/base:20200204-1
COPY etc/zookeeper/zoo.cfg /opt/apache-zookeeper/conf/zookeeper.properties
COPY etc/kafka/server.properties /etc/kafka/server.properties.template
COPY scripts/runServer /root/runServer
COPY scripts/configureSSL.pl /root/configureSSL.pl
RUN  chmod ugo+rx /root/runServer /root/configureSSL.pl
RUN  mkdir -p /root/shared/tls
WORKDIR /tmp
EXPOSE 9092/tcp
ENTRYPOINT ["/root/runServer"]
