name: Build
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-18.04
    name:    build
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: make
        run:  make
      - name: installPython
        uses: actions/setup-python@v1
      - name: install pytest
        run:  pip3 install pytest
        with:
          python-version: '3.6'
      - name: test
        run:  make test
