name: Build
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-18.04
    name: build
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: make
      - name:
        run: make test
