name: Release
on:
  release:
    types: [published, created]
jobs:
  release:
    runs-on: ubuntu-18.04
    name:    release
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: make
        run:  make
      - name: test
        run:  make test
      - name: env
        with: BUILDER: ${{ secrets.BUILDER }}
        run:  echo "=========== ENV =========="; env; echo "========================"
      - name: pwd
        run:  echo "pwd: " `pwd`
