name: Release
on:
  push:
    branches-ignore:
      - '!master'
    tags:
      - 'version-*'
        
jobs:
  release:
    runs-on: ubuntu-18.04
    name:    release
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: make
        run:  make
      - name: test
        run:  make test
      - name: env
        env: 
          BUILDER: ${{ secrets.BUILDER }}
        run:  env
      - name: ls
        run: ls
      - name: pwd
        run: pwd
