name: Release
on:
  push:
    tags:
      - 'version-*'

jobs:
  release:
    runs-on: ubuntu-18.04
    name:    release
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: make
        run:  make
      - name: test
        run:  make test
      - name: push
        env:
          BUILDER: ${{ secrets.BUILDER }}
          BUILDERCRED: ${{ secrets.BUILDERCRED }}
        run: make push
